server:
  port: 8083

spring:
  application:
    name: personal-finance-gateway
  jackson:
    default-property-inclusion: non-null
    property-naming-strategy: SNAKE_CASE
    serialization:
      write-dates-as-timestamps: false
      indent-output: false


account-service-api:
  url: http://ec2-3-88-43-183.compute-1.amazonaws.com:8082

personal-finance-api:
  url: http://ec2-3-88-43-183.compute-1.amazonaws.com:8081

